name: Release Workflow

on:
  push:
    tags:
        - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
   release:
    name: Release Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - name: Build Package
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install setuptools wheel
        python setup.py bdist_wheel
    - name: Publish Package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*
    - name: Sleep
      run: sleep 30s
      shell: bash
    - name: Login to container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata for Docker Image
      env:
        IMAGE_NAME: ${{ github.repository }}
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and Publish Docker Image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}